//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int postNumber { get; set; }
        public Nullable<int> userId { get; set; }
        public string content { get; set; }
        public Nullable<int> likes { get; set; }
    }
}
